#pragma once

#include <furi.h>

#include <gui/view.h>

/* generated by fbt from .png files in images folder */
#include <ldtoypad_icons.h>

#ifdef __cplusplus
extern "C" {
#endif

void ldtoypad_main_menu_scene_draw(Canvas* canvas, void* context);
bool ldtoypad_main_menu_scene_input_callback(InputEvent* event, void* context);

#ifdef __cplusplus
}
#endif
