#include "sub_screens.h"

#include <gui/elements.h>

/* generated by fbt from .png files in images folder */
#include <ldtoypad_icons.h>

void draw_minifigure_vehicle_screen(Canvas* canvas, bool minfig_box_selected) {
    canvas_set_font(canvas, FontPrimary);
    canvas_set_color(canvas, ColorBlack);

    canvas_draw_str(canvas, 10, 14, "Select a type to place");

    elements_button_left(canvas, "Back");

    if(minfig_box_selected) {
        canvas_draw_str(canvas, 40, 57, "Minifigure");
        canvas_draw_icon(canvas, 22, 23, &I_minifig_selected);

        // make vehicle not selected
        canvas_draw_icon(canvas, 67, 23, &I_box_longer);
        canvas_draw_icon(canvas, 72, 26, &I_car_bigger);

    } else {
        canvas_draw_str(canvas, 40, 57, "Vehicle");
        canvas_draw_icon(canvas, 67, 23, &I_car_bigger_selected);

        // make minifig not selected
        canvas_draw_icon(canvas, 22, 23, &I_box_longer);
        canvas_draw_icon(canvas, 34, 25, &I_head);
    }
}
